[deps]
Augmentor = "02898b10-1f73-11ea-317c-6393d7073e15"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GRUtils = "0337cf30-a0fd-11e9-31db-a79914c9d7ac"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
